// <auto-generated />
using System;
using InventoryLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251010123235_ChangedPersonInCharge")]
    partial class ChangedPersonInCharge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryLibrary.Model.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemConditionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("addedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("imagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("itemPrice")
                        .HasColumnType("float");

                    b.Property<double>("itemWeight")
                        .HasColumnType("float");

                    b.Property<DateTime>("lastInventoryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("personInChargeId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("warrantyEnd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ItemConditionId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("RoomId");

                    b.HasIndex("personInChargeId");

                    b.ToTable("InventoryItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.ItemCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemConditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConditionName = "New"
                        },
                        new
                        {
                            Id = 2,
                            ConditionName = "Good"
                        },
                        new
                        {
                            Id = 3,
                            ConditionName = "Damaged"
                        },
                        new
                        {
                            Id = 4,
                            ConditionName = "Lost"
                        },
                        new
                        {
                            Id = 5,
                            ConditionName = "Disposed"
                        });
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "NoType"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "AGD"
                        },
                        new
                        {
                            Id = 3,
                            TypeName = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            TypeName = "Book"
                        });
                });

            modelBuilder.Entity("InventoryLibrary.Model.Location.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("InventoryLibrary.Model.Location.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.AGD", b =>
                {
                    b.HasBaseType("InventoryLibrary.Model.Inventory.InventoryItem");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Graphics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AGD", (string)null);
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.Furniture", b =>
                {
                    b.HasBaseType("InventoryLibrary.Model.Inventory.InventoryItem");

                    b.Property<string>("FurnitureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Furniture", (string)null);
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.InventoryItem", b =>
                {
                    b.HasOne("InventoryLibrary.Model.Inventory.ItemCondition", "ItemCondition")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryLibrary.Model.Inventory.ItemType", "ItemType")
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryLibrary.Model.Location.Room", "Location")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InventoryLibrary.Model.Accounts.Account", "personInCharge")
                        .WithMany()
                        .HasForeignKey("personInChargeId");

                    b.Navigation("ItemCondition");

                    b.Navigation("ItemType");

                    b.Navigation("Location");

                    b.Navigation("personInCharge");
                });

            modelBuilder.Entity("InventoryLibrary.Model.Location.Room", b =>
                {
                    b.HasOne("InventoryLibrary.Model.Location.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.AGD", b =>
                {
                    b.HasOne("InventoryLibrary.Model.Inventory.InventoryItem", null)
                        .WithOne()
                        .HasForeignKey("InventoryLibrary.Model.Inventory.AGD", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.Furniture", b =>
                {
                    b.HasOne("InventoryLibrary.Model.Inventory.InventoryItem", null)
                        .WithOne()
                        .HasForeignKey("InventoryLibrary.Model.Inventory.Furniture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.ItemCondition", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("InventoryLibrary.Model.Inventory.ItemType", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("InventoryLibrary.Model.Location.Department", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
